# **I.A para multiplicar.**

Pregunta 2

Autor: Claudio Vergara

IA para negocios

Ingenieria Civil Industrial

Universidad Austral de Chile

Profesor: Luis Vidal

Caso: Se tiene un set de datos que mediante la mutilpicacion de las variables productividad (P), mano de obra (MO) y una constante de población (CP), se obtiene la función producción (en terminos microeconomicos). Se requiere emplear una red neuronal que permita multiplicar dichos valores y obrener el valor de la producción neta.



# Importar librerias

In [ ]:
import pandas as pd
import numpy as np

# Carga de datos

In [ ]:
# Se emple la función wget que permita bajar al espacio de trabajo los datos para análisis
!wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/klaudius20/produccion/main/Producci%C3%B3n.csv

# Ustilizando pandas, se carga archivo en memoria como dataframe
df = pd.read_csv("Producción.csv")
df.head(10)

--2021-11-07 17:12:51--  https://raw.githubusercontent.com/klaudius20/produccion/main/Producci%C3%B3n.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8812 (8.6K) [text/plain]
Saving to: ‘Producción.csv.1’

Producción.csv.1    100%[===================>]   8.61K  --.-KB/s    in 0s      

2021-11-07 17:12:51 (65.2 MB/s) - ‘Producción.csv.1’ saved [8812/8812]



Prod    P   MO   CP
0   66885000  147  910  500
1   68113500  875  998   78
2  106929408  852  212  592
3    4404092  362  158   77
4    3218904   57  543  104
5  807633134  971  982  847
6   85492575  525  309  527
7   38066220  449  540  157
8   37242350  491  185  410
9   11255790  741   49  310

In [ ]:
df = pd.read_csv('Producción.csv')

In [ ]:
#Muestra columnas
print(df.columns)

Index(['Prod', 'P', 'MO', 'CP'], dtype='object')


In [ ]:
#Creamos un dataset desde el archivo que se descargo.
dataset = df.values

In [ ]:
print(dataset)

[[ 66885000       147       910       500]
 [ 68113500       875       998        78]
 [106929408       852       212       592]
 ...
 [ 71779136       506       352       403]
 [337254704       713       752       629]
 [294139384       523       616       913]]


In [ ]:
#Separamos los datos Y=prod variable objetivo, X variables P, MO y CP
Y=dataset[:,0]
X=dataset[:,1:4]

In [ ]:
#Usar este código para dejar los tipos de datos como float, sugerido.
X=np.asarray(X).astype(np.float32)
Y=np.asarray(Y).astype(np.float32)

In [ ]:
print(X)
print(Y)

[[147. 910. 500.]
 [875. 998.  78.]
 [852. 212. 592.]
 ...
 [506. 352. 403.]
 [713. 752. 629.]
 [523. 616. 913.]]
[6.68850000e+07 6.81135040e+07 1.06929408e+08 4.40409200e+06
 3.21890400e+06 8.07633152e+08 8.54925760e+07 3.80662200e+07
 3.72423520e+07 1.12557900e+07 3.63324000e+07 1.35177008e+08
 5.45078320e+07 1.39607152e+08 7.03325440e+07 7.74219900e+06
 8.73493500e+06 4.54340200e+07 1.47803040e+08 5.04062640e+07
 1.55553232e+08 3.01824000e+07 2.54018512e+08 7.35927600e+07
 1.81298880e+08 3.15447840e+07 1.98000000e+06 6.07426560e+07
 1.67540944e+08 1.94347008e+08 1.64656080e+07 9.29260000e+07
 3.21084224e+08 5.42100000e+06 2.66446272e+08 4.61712480e+07
 4.74476800e+07 2.46949344e+08 1.19498600e+08 1.02921000e+08
 1.37420010e+07 6.26944000e+05 1.89836400e+08 9.23981440e+07
 5.14290240e+07 4.53407008e+08 4.53816000e+07 1.89618240e+08
 1.81876608e+08 5.10239840e+08 1.00349280e+08 4.53197760e+08
 2.09927024e+08 2.70290720e+08 2.97432000e+07 3.41077520e+07
 9.24976800e+07 2.29050720e+07 2

# Creación del Cerebro de la I.A.

Se pretende utlizar tres capas ocultas, las cuales cada una tiene 18, 36 y 27 neuronas respectivamente, utilizando la funcion de activacion sigmoid.

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
#Cerebro
def build_model():
  model = keras.Sequential([
    layers.Dense(18, activation='sigmoid', input_shape=[3]),   #input_shape  se ingresa cantida de Xi
    layers.Dense(36, activation='sigmoid'),
    layers.Dense(27, activation='sigmoid'),
    layers.Dense(1)
  ])
  optimizer = tf.keras.optimizers.RMSprop(learning_rate=0.0001)
  model.compile(loss='mse',
                optimizer=optimizer,
                metrics=['mae', 'mse'])
  return model

In [ ]:
#Se crea el modelo Cerebro (modelo de redes neuronales)
model = build_model()

# Entrenamiento de la Red Neuronal

Se pretende utlizar un EPOCHS de 10000

In [ ]:
!pip install git+https://github.com/tensorflow/docs

  Cloning https://github.com/tensorflow/docs to /tmp/pip-req-build-ahiedb6z
  Running command git clone -q https://github.com/tensorflow/docs /tmp/pip-req-build-ahiedb6z
  Created wheel for tensorflow-docs: filename=tensorflow_docs-0.0.0.dev0-py3-none-any.whl size=157855 sha256=1194cc8f7bd27b247248316d8d7d49020f186b0ba1b2c87bef0b416ec201e24e
  Stored in directory: /tmp/pip-ephem-wheel-cache-n02gl5dn/wheels/cc/c4/d8/5341e93b6376c5c929c49469fce21155eb69cef1a4da4ce32c
Successfully built tensorflow-docs


In [ ]:
import tensorflow_docs as tfdocs
import tensorflow_docs.modeling

In [ ]:
EPOCHS = 10000

In [ ]:
history = model.fit(
    X,Y,
    epochs=EPOCHS, verbose=0,
    callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, loss:41168124820586496.0000,  mae:134390800.0000,  mse:41168124820586496.0000,  
....................................................................................................
Epoch: 100, loss:41168129115553792.0000,  mae:134390800.0000,  mse:41168129115553792.0000,  
....................................................................................................
Epoch: 200, loss:41168124820586496.0000,  mae:134390784.0000,  mse:41168124820586496.0000,  
....................................................................................................
Epoch: 300, loss:41168129115553792.0000,  mae:134390768.0000,  mse:41168129115553792.0000,  
....................................................................................................
Epoch: 400, loss:41168124820586496.0000,  mae:134390768.0000,  mse:41168124820586496.0000,  
....................................................................................................
Epoch: 500, loss:41168124820586

# Prueba de la I.A. creada, que tenía como objeto multiplicar los valores de productividad, mano de obra y constante poblacional para entregar la produccion neta.

In [ ]:
print("Produccion neta")

a=float(input("Ingrese productividad: "))
b=float(input("Ingrese mano de obra: "))
c=float(input("Ingrese constante pobalcional: "))

y=model.predict(np.array([[a,b,c]]))

#produccion=a*b*c
#error_absoluto=abs(produccion-y)

print(" ")
print("El resultado es: %s apróximadamente " % y[0] [0])


#print(" ")
#print("El error absoluto es de %s:" % error_absoluto[0][0])


Produccion neta
Ingrese productividad: 900
Ingrese mano de obra: 900
Ingrese constante pobalcional: 900
 
El resultado es: 355.6614 apróximadamente 
